### ISSUE TITLE
Edit the tree by dragging and dropping nodes

### ISSUE THREAD

**Issue by maxclac** [jupyter-widgets-contrib/ipytree#26]
Hello everyone! 

I was thinking it would be nice to be able to edit the tree by dragging and dropping nodes. Would that be possible to implement?

Best regards

**Comment by martinRenou** [comment]
Hey,

It would be possible indeed. jsTree has a drag and drop plugin that we could use https://www.jstree.com/plugins.

Anyone willing to contribute is very welcome to add this to ipytree :)

**Comment by fiatluxadmin** [comment]
@martinRenou - IIve been using ipytree (and ipywidgets) extensively within my notebooks to provide a framework for exploratory data analysis for my users. I've long desired this capability and figure it's time I dived in. I have a bit of time to devote to this now, though it's not really my area of expertise. If you could map out the pre-requisite areas of competence/understanding from ipwywidgets that I will need to grok,  I'm willing to do the homework and give it a shot.

**Comment by maxclac** [comment]
That would be awesome! Thanks!

**Comment by martinRenou** [comment]
That's great to hear! Thanks!

You need to write a bit of JavaScript. So the main JavaScript code in ipytree is here: https://github.com/QuantStack/ipytree/blob/master/js/lib/tree.js, this is where the actual Tree and Nodes are created and added to the page.

I don't think you need to know much about ipywidgets for now, you can start hacking this JavaScript file and I can drive you through finishing it if you open a PR with what you started :)

I guess you can just start by allowing drag and drop on the tree JavaScript side, then we might need to figure out a way for the Python models to be properly updated upon drop.
Our tree is created here: https://github.com/QuantStack/ipytree/blob/master/js/lib/tree.js#L252
And the drag and drop plugin can be added here: https://github.com/QuantStack/ipytree/blob/master/js/lib/tree.js#L258

This is the list of jstree (The JavaScript library we use for displaying a tree) plugins: https://www.jstree.com/plugins
This is the jstree API: https://www.jstree.com/api/#/?q=$.jstree.defaults.dnd&f=$.jstree.defaults.dnd

**Comment by Poompil** [comment]
Wondering if @fiatluxadmin (or anyone else) has been able to make any progress on this issue. Would be really interested in this feature myself, and also willing to contribute to the development.

**Comment by JoelStansbury** [comment]
@martinRenou I think I've got a working solution, is it ok if I make a PR?

**Comment by JoelStansbury** [comment]
> @martinRenou I think I've got a working solution, is it ok if I make a PR?

Well, mostly working, there are a few bugs that are giving me trouble

**Comment by martinRenou** [comment]
Feel free to open a PR!

**Comment by JoelStansbury** [comment]
@martinRenou Ok, the bugs have been resolved. PR is ready for review
