### ISSUE TITLE
Alive?

### ISSUE THREAD

**Issue by martindurant** [jupyter-widgets-contrib/ipytree#87]
Is this project still maintained, and can I expect it to work with the latest versions of jlab/jwidgets?

**Comment by martinRenou** [comment]
Just tried with jupyterlab v4 and ipywidgets v8.1.1, works like a charm

![Screenshot from 2024-02-08 09-04-13](https://github.com/jupyter-widgets-contrib/ipytree/assets/21197331/c16c4589-49df-4005-91c7-0f7b6495e1b5)

Do you have issues/feature requests in mind? Would you be willing to help the maintenance of the project?

**Comment by martindurant** [comment]
Thanks for checking it out. I have too many things to maintain as it is, and UI/JS are not my strengths. I was thinking the tree would be a nice improvement to https://filesystem-spec.readthedocs.io/en/latest/features.html#file-selector-gui

**Comment by martinRenou** [comment]
We'll try to make sure ipytree continues working through new jupyterlab and ipywidgets versions

**Comment by martindurant** [comment]
+1
